# Generated by Django 3.2.3 on 2021-05-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageManager',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
