# Generated by Django 3.2.3 on 2021-05-31 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0006_auto_20210530_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
